// Generated by CoffeeScript 1.4.0
(function() {
  var _base,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.JST || (window.JST = {});

  window.JST['loop'] = _.template("<h1>Loop View</h1>");

  window.Backbone || (window.Backbone = {});

  (_base = window.Backbone).Views || (_base.Views = {});

  Backbone.Views.LoopView = (function(_super) {

    __extends(LoopView, _super);

    function LoopView() {
      this.render = __bind(this.render, this);
      return LoopView.__super__.constructor.apply(this, arguments);
    }

    LoopView.prototype.template = JST['loop'];

    LoopView.prototype.initialize = function(options) {
      return this.render();
    };

    LoopView.prototype.render = function() {
      return this.$el.html(this.template());
    };

    LoopView.prototype.onClose = function() {};

    return LoopView;

  })(Backbone.View);

}).call(this);
